# config/packages/flysystem.yaml
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                # Храним файлы ВНЕ папки public, чтобы их нельзя было открыть по прямой ссылке
                # Это критично для паспортов и уставных документов!
                directory: '%kernel.project_dir%/var/storage'
