# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      '%env(JWT_PASSPHRASE)%' # <-- Используем наш пароль из .env
    token_ttl:        3600 # (Токен "живет" 1 час)
