# Используем PHP 8.4 (чтобы совпадало с вашим composer.lock)
FROM php:8.4-apache

# Устанавливаем расширения
RUN apt-get update && apt-get install -y \
    libicu-dev \
    libpq-dev \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-install intl pdo pdo_pgsql zip opcache

# Включаем mod_rewrite для Apache
RUN a2enmod rewrite

# Настраиваем Apache
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf

# Копируем composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Копируем код
WORKDIR /var/www/html
COPY . .

# Устанавливаем зависимости
RUN composer install --no-dev --optimize-autoloader

# --- ИСПРАВЛЕНИЕ ЗДЕСЬ ---
# Создаем папку var (кеш/логи), так как её нет в git
RUN mkdir -p var

# Права доступа
RUN chown -R www-data:www-data var
# -------------------------

# Генерируем ключи JWT
RUN mkdir -p config/jwt
RUN openssl genrsa -out config/jwt/private.pem 4096
RUN openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
RUN chown -R www-data:www-data config/jwt

# --- ДОБАВЛЯЕМ ЭТО ---
# Копируем скрипт запуска
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# Делаем его исполняемым (важно!)
RUN chmod +x /usr/local/bin/entrypoint.sh

# Говорим Docker'у использовать этот скрипт как точку входа
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Открываем порт
EXPOSE 80
