<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251116144842 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, amount NUMERIC(15, 2) NOT NULL, term_days INT NOT NULL, product_data JSON NOT NULL, offer_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_user_id INT NOT NULL, agent_user_id INT DEFAULT NULL, bank_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A45BDDC1F55397E8 ON application (client_user_id)');
        $this->addSql('CREATE INDEX IDX_A45BDDC1753DB13F ON application (agent_user_id)');
        $this->addSql('CREATE INDEX IDX_A45BDDC111C8FB41 ON application (bank_id)');
        $this->addSql('CREATE TABLE bank (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, logo_path VARCHAR(255) DEFAULT NULL, conditions JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE client_agent_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, agent_user_id INT NOT NULL, client_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B631E53753DB13F ON client_agent_link (agent_user_id)');
        $this->addSql('CREATE INDEX IDX_B631E53F55397E8 ON client_agent_link (client_user_id)');
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, full_name TEXT NOT NULL, inn VARCHAR(12) NOT NULL, ogrn VARCHAR(15) NOT NULL, legal_address TEXT NOT NULL, ceo_fio VARCHAR(255) NOT NULL, tax_system VARCHAR(50) NOT NULL, requisites JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094FE93323CB ON company (inn)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094FA76ED395 ON company (user_id)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, doc_type VARCHAR(100) NOT NULL, file_name VARCHAR(255) NOT NULL, file_path TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploader_user_id INT NOT NULL, company_id INT DEFAULT NULL, application_id INT DEFAULT NULL, message_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76CC16E2A2 ON document (uploader_user_id)');
        $this->addSql('CREATE INDEX IDX_D8698A76979B1AD6 ON document (company_id)');
        $this->addSql('CREATE INDEX IDX_D8698A763E030ACD ON document (application_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D8698A76537A1329 ON document (message_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, moderation_status VARCHAR(20) NOT NULL, read_status BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, application_id INT NOT NULL, sender_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F3E030ACD ON message (application_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F2A98155E ON message (sender_user_id)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, fio VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, personal_manager_id INT DEFAULT NULL, referrer_agent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON "users" (email)');
        $this->addSql('CREATE INDEX IDX_1483A5E938EE93C3 ON "users" (personal_manager_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E96FFE1673 ON "users" (referrer_agent_id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1F55397E8 FOREIGN KEY (client_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1753DB13F FOREIGN KEY (agent_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC111C8FB41 FOREIGN KEY (bank_id) REFERENCES bank (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client_agent_link ADD CONSTRAINT FK_B631E53753DB13F FOREIGN KEY (agent_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client_agent_link ADD CONSTRAINT FK_B631E53F55397E8 FOREIGN KEY (client_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76CC16E2A2 FOREIGN KEY (uploader_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A763E030ACD FOREIGN KEY (application_id) REFERENCES application (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76537A1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F3E030ACD FOREIGN KEY (application_id) REFERENCES application (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F2A98155E FOREIGN KEY (sender_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E938EE93C3 FOREIGN KEY (personal_manager_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E96FFE1673 FOREIGN KEY (referrer_agent_id) REFERENCES "users" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC1F55397E8');
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC1753DB13F');
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC111C8FB41');
        $this->addSql('ALTER TABLE client_agent_link DROP CONSTRAINT FK_B631E53753DB13F');
        $this->addSql('ALTER TABLE client_agent_link DROP CONSTRAINT FK_B631E53F55397E8');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094FA76ED395');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76CC16E2A2');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76979B1AD6');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A763E030ACD');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76537A1329');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F3E030ACD');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F2A98155E');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E938EE93C3');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E96FFE1673');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE bank');
        $this->addSql('DROP TABLE client_agent_link');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE "users"');
    }
}
