<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251119213538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "companies" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, full_name TEXT NOT NULL, inn VARCHAR(12) NOT NULL, kpp VARCHAR(9) DEFAULT NULL, ogrn VARCHAR(15) NOT NULL, legal_address TEXT NOT NULL, actual_address TEXT DEFAULT NULL, registration_date DATE DEFAULT NULL, okpo VARCHAR(20) DEFAULT NULL, oktmo VARCHAR(20) DEFAULT NULL, okved VARCHAR(20) DEFAULT NULL, authorized_capital NUMERIC(15, 2) DEFAULT NULL, paid_capital NUMERIC(15, 2) DEFAULT NULL, tax_system VARCHAR(50) NOT NULL, employee_count INT DEFAULT NULL, contract_count INT DEFAULT NULL, requisites JSON DEFAULT \'[]\' NOT NULL, management JSON DEFAULT NULL, founders JSON DEFAULT NULL, licenses JSON DEFAULT NULL, contact_persons JSON DEFAULT NULL, etp_accounts JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, web_site VARCHAR(255) DEFAULT NULL, office_phone VARCHAR(50) DEFAULT NULL, vat_rate VARCHAR(10) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AE93323CB ON "companies" (inn)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AA76ED395 ON "companies" (user_id)');
        $this->addSql('CREATE TABLE "documents" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_archived BOOLEAN DEFAULT false NOT NULL, version_comment TEXT DEFAULT NULL, doc_type VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, rejection_reason TEXT DEFAULT NULL, file_name VARCHAR(255) NOT NULL, file_path TEXT NOT NULL, file_size INT DEFAULT NULL, mime_type VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploader_user_id INT NOT NULL, company_id INT DEFAULT NULL, application_id INT DEFAULT NULL, message_id INT DEFAULT NULL, parent_document_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2B07288CC16E2A2 ON "documents" (uploader_user_id)');
        $this->addSql('CREATE INDEX IDX_A2B07288979B1AD6 ON "documents" (company_id)');
        $this->addSql('CREATE INDEX IDX_A2B072883E030ACD ON "documents" (application_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2B07288537A1329 ON "documents" (message_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2B07288A8136A47 ON "documents" (parent_document_id)');
        $this->addSql('CREATE TABLE news (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_published BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE "companies" ADD CONSTRAINT FK_8244AA3AA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288CC16E2A2 FOREIGN KEY (uploader_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B072883E030ACD FOREIGN KEY (application_id) REFERENCES application (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288537A1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288A8136A47 FOREIGN KEY (parent_document_id) REFERENCES "documents" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT fk_4fbf094fa76ed395');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT fk_d8698a76cc16e2a2');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT fk_d8698a76979b1ad6');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT fk_d8698a763e030acd');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT fk_d8698a76537a1329');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE document');
        $this->addSql('ALTER TABLE application ADD commission_amount NUMERIC(15, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE application ADD tariff_rate DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD preferences JSON DEFAULT \'{}\' NOT NULL');
        $this->addSql('ALTER TABLE users ADD gender VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD timezone VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD avatar_path VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, full_name TEXT NOT NULL, inn VARCHAR(12) NOT NULL, ogrn VARCHAR(15) NOT NULL, legal_address TEXT NOT NULL, ceo_fio VARCHAR(255) NOT NULL, tax_system VARCHAR(50) NOT NULL, requisites JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_4fbf094fa76ed395 ON company (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_4fbf094fe93323cb ON company (inn)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, doc_type VARCHAR(100) NOT NULL, file_name VARCHAR(255) NOT NULL, file_path TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploader_user_id INT NOT NULL, company_id INT DEFAULT NULL, application_id INT DEFAULT NULL, message_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d8698a76979b1ad6 ON document (company_id)');
        $this->addSql('CREATE INDEX idx_d8698a76cc16e2a2 ON document (uploader_user_id)');
        $this->addSql('CREATE INDEX idx_d8698a763e030acd ON document (application_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_d8698a76537a1329 ON document (message_id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT fk_4fbf094fa76ed395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT fk_d8698a76cc16e2a2 FOREIGN KEY (uploader_user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT fk_d8698a76979b1ad6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT fk_d8698a763e030acd FOREIGN KEY (application_id) REFERENCES application (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT fk_d8698a76537a1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "companies" DROP CONSTRAINT FK_8244AA3AA76ED395');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288CC16E2A2');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288979B1AD6');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B072883E030ACD');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288537A1329');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288A8136A47');
        $this->addSql('DROP TABLE "companies"');
        $this->addSql('DROP TABLE "documents"');
        $this->addSql('DROP TABLE news');
        $this->addSql('ALTER TABLE application DROP commission_amount');
        $this->addSql('ALTER TABLE application DROP tariff_rate');
        $this->addSql('ALTER TABLE "users" DROP preferences');
        $this->addSql('ALTER TABLE "users" DROP gender');
        $this->addSql('ALTER TABLE "users" DROP timezone');
        $this->addSql('ALTER TABLE "users" DROP avatar_path');
    }
}
