<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124182146 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE instructions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content TEXT NOT NULL, category VARCHAR(100) NOT NULL, order_index INT NOT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_997D812B989D9B62 ON instructions (slug)');
        $this->addSql('CREATE TABLE support_tickets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, attachment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E9739508A76ED395 ON support_tickets (user_id)');
        $this->addSql('CREATE INDEX IDX_E9739508464E68B ON support_tickets (attachment_id)');
        $this->addSql('ALTER TABLE support_tickets ADD CONSTRAINT FK_E9739508A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE support_tickets ADD CONSTRAINT FK_E9739508464E68B FOREIGN KEY (attachment_id) REFERENCES "uploaded_files" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE support_tickets DROP CONSTRAINT FK_E9739508A76ED395');
        $this->addSql('ALTER TABLE support_tickets DROP CONSTRAINT FK_E9739508464E68B');
        $this->addSql('DROP TABLE instructions');
        $this->addSql('DROP TABLE support_tickets');
    }
}
