<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251119214225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, amount NUMERIC(15, 2) NOT NULL, term_days INT NOT NULL, product_data JSON NOT NULL, offer_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commission_amount NUMERIC(15, 2) DEFAULT NULL, tariff_rate DOUBLE PRECISION DEFAULT NULL, client_user_id INT NOT NULL, agent_user_id INT DEFAULT NULL, bank_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A45BDDC1F55397E8 ON application (client_user_id)');
        $this->addSql('CREATE INDEX IDX_A45BDDC1753DB13F ON application (agent_user_id)');
        $this->addSql('CREATE INDEX IDX_A45BDDC111C8FB41 ON application (bank_id)');
        $this->addSql('CREATE TABLE bank (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, logo_path VARCHAR(255) DEFAULT NULL, conditions JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE client_agent_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, agent_user_id INT NOT NULL, client_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B631E53753DB13F ON client_agent_link (agent_user_id)');
        $this->addSql('CREATE INDEX IDX_B631E53F55397E8 ON client_agent_link (client_user_id)');
        $this->addSql('CREATE TABLE "companies" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, full_name TEXT NOT NULL, inn VARCHAR(12) NOT NULL, kpp VARCHAR(9) DEFAULT NULL, ogrn VARCHAR(15) NOT NULL, legal_address TEXT NOT NULL, actual_address TEXT DEFAULT NULL, registration_date DATE DEFAULT NULL, okpo VARCHAR(20) DEFAULT NULL, oktmo VARCHAR(20) DEFAULT NULL, okved VARCHAR(20) DEFAULT NULL, authorized_capital NUMERIC(15, 2) DEFAULT NULL, paid_capital NUMERIC(15, 2) DEFAULT NULL, tax_system VARCHAR(50) NOT NULL, employee_count INT DEFAULT NULL, contract_count INT DEFAULT NULL, requisites JSON DEFAULT \'[]\' NOT NULL, management JSON DEFAULT NULL, founders JSON DEFAULT NULL, licenses JSON DEFAULT NULL, contact_persons JSON DEFAULT NULL, etp_accounts JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, web_site VARCHAR(255) DEFAULT NULL, office_phone VARCHAR(50) DEFAULT NULL, vat_rate VARCHAR(10) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AE93323CB ON "companies" (inn)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AA76ED395 ON "companies" (user_id)');
        $this->addSql('CREATE TABLE "documents" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_archived BOOLEAN DEFAULT false NOT NULL, version_comment TEXT DEFAULT NULL, doc_type VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, rejection_reason TEXT DEFAULT NULL, file_name VARCHAR(255) NOT NULL, file_path TEXT NOT NULL, file_size INT DEFAULT NULL, mime_type VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploader_user_id INT NOT NULL, company_id INT DEFAULT NULL, application_id INT DEFAULT NULL, message_id INT DEFAULT NULL, parent_document_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2B07288CC16E2A2 ON "documents" (uploader_user_id)');
        $this->addSql('CREATE INDEX IDX_A2B07288979B1AD6 ON "documents" (company_id)');
        $this->addSql('CREATE INDEX IDX_A2B072883E030ACD ON "documents" (application_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2B07288537A1329 ON "documents" (message_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2B07288A8136A47 ON "documents" (parent_document_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, moderation_status VARCHAR(20) NOT NULL, read_status BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, application_id INT NOT NULL, sender_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F3E030ACD ON message (application_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F2A98155E ON message (sender_user_id)');
        $this->addSql('CREATE TABLE news (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_published BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, fio VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, preferences JSON DEFAULT \'{}\' NOT NULL, gender VARCHAR(10) DEFAULT NULL, timezone VARCHAR(50) DEFAULT NULL, avatar_path VARCHAR(255) DEFAULT NULL, personal_manager_id INT DEFAULT NULL, referrer_agent_id INT DEFAULT NULL, bank_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON "users" (email)');
        $this->addSql('CREATE INDEX IDX_1483A5E938EE93C3 ON "users" (personal_manager_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E96FFE1673 ON "users" (referrer_agent_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E911C8FB41 ON "users" (bank_id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1F55397E8 FOREIGN KEY (client_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1753DB13F FOREIGN KEY (agent_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC111C8FB41 FOREIGN KEY (bank_id) REFERENCES bank (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client_agent_link ADD CONSTRAINT FK_B631E53753DB13F FOREIGN KEY (agent_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client_agent_link ADD CONSTRAINT FK_B631E53F55397E8 FOREIGN KEY (client_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "companies" ADD CONSTRAINT FK_8244AA3AA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288CC16E2A2 FOREIGN KEY (uploader_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B072883E030ACD FOREIGN KEY (application_id) REFERENCES application (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288537A1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288A8136A47 FOREIGN KEY (parent_document_id) REFERENCES "documents" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F3E030ACD FOREIGN KEY (application_id) REFERENCES application (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F2A98155E FOREIGN KEY (sender_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E938EE93C3 FOREIGN KEY (personal_manager_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E96FFE1673 FOREIGN KEY (referrer_agent_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E911C8FB41 FOREIGN KEY (bank_id) REFERENCES bank (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC1F55397E8');
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC1753DB13F');
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC111C8FB41');
        $this->addSql('ALTER TABLE client_agent_link DROP CONSTRAINT FK_B631E53753DB13F');
        $this->addSql('ALTER TABLE client_agent_link DROP CONSTRAINT FK_B631E53F55397E8');
        $this->addSql('ALTER TABLE "companies" DROP CONSTRAINT FK_8244AA3AA76ED395');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288CC16E2A2');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288979B1AD6');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B072883E030ACD');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288537A1329');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288A8136A47');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F3E030ACD');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F2A98155E');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E938EE93C3');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E96FFE1673');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E911C8FB41');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE bank');
        $this->addSql('DROP TABLE client_agent_link');
        $this->addSql('DROP TABLE "companies"');
        $this->addSql('DROP TABLE "documents"');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE "users"');
    }
}
