<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251123205904 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent_client_interactions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, notes TEXT NOT NULL, interaction_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agent_user_id INT NOT NULL, client_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_agent ON agent_client_interactions (agent_user_id)');
        $this->addSql('CREATE INDEX idx_client ON agent_client_interactions (client_user_id)');
        $this->addSql('CREATE INDEX idx_interaction_date ON agent_client_interactions (interaction_date)');
        $this->addSql('CREATE INDEX idx_agent_client ON agent_client_interactions (agent_user_id, client_user_id)');
        $this->addSql('CREATE TABLE agent_commissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, commission_rate NUMERIC(5, 2) NOT NULL, commission_amount NUMERIC(15, 2) NOT NULL, status VARCHAR(255) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agent_user_id INT NOT NULL, application_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_agent_commission ON agent_commissions (agent_user_id)');
        $this->addSql('CREATE INDEX idx_commission_status ON agent_commissions (status)');
        $this->addSql('CREATE INDEX idx_commission_created_at ON agent_commissions (created_at)');
        $this->addSql('CREATE UNIQUE INDEX unique_commission_per_application ON agent_commissions (application_id)');
        $this->addSql('CREATE TABLE application_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_status VARCHAR(50) NOT NULL, new_status VARCHAR(50) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, application_id INT NOT NULL, changed_by_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_history_application ON application_status_history (application_id)');
        $this->addSql('CREATE INDEX idx_changed_by ON application_status_history (changed_by_user_id)');
        $this->addSql('CREATE INDEX idx_history_created_at ON application_status_history (created_at)');
        $this->addSql('CREATE INDEX idx_app_created ON application_status_history (application_id, created_at)');
        $this->addSql('CREATE TABLE applications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, amount NUMERIC(15, 2) NOT NULL, term_days INT NOT NULL, product_data JSON NOT NULL, offer_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commission_amount NUMERIC(15, 2) DEFAULT NULL, tariff_rate DOUBLE PRECISION DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_user_id INT NOT NULL, agent_user_id INT DEFAULT NULL, bank_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_client_user ON applications (client_user_id)');
        $this->addSql('CREATE INDEX idx_agent_user ON applications (agent_user_id)');
        $this->addSql('CREATE INDEX idx_application_bank ON applications (bank_id)');
        $this->addSql('CREATE INDEX idx_app_status ON applications (status)');
        $this->addSql('CREATE INDEX idx_product_type ON applications (product_type)');
        $this->addSql('CREATE INDEX idx_app_created_at ON applications (created_at)');
        $this->addSql('CREATE INDEX idx_updated_at ON applications (updated_at)');
        $this->addSql('CREATE INDEX idx_status_product ON applications (status, product_type)');
        $this->addSql('CREATE TABLE banks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, logo_path VARCHAR(255) DEFAULT NULL, conditions JSON NOT NULL, status VARCHAR(255) NOT NULL, accreditation_status VARCHAR(255) NOT NULL, accreditation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rejection_reason TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bank_status ON banks (status)');
        $this->addSql('CREATE INDEX idx_bank_accreditation ON banks (accreditation_status)');
        $this->addSql('CREATE TABLE client_agent_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, agent_user_id INT NOT NULL, client_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B631E53753DB13F ON client_agent_link (agent_user_id)');
        $this->addSql('CREATE INDEX IDX_B631E53F55397E8 ON client_agent_link (client_user_id)');
        $this->addSql('CREATE TABLE "companies" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, full_name TEXT NOT NULL, inn VARCHAR(12) NOT NULL, kpp VARCHAR(9) DEFAULT NULL, ogrn VARCHAR(15) NOT NULL, legal_address TEXT NOT NULL, ceo_fio VARCHAR(255) NOT NULL, actual_address TEXT DEFAULT NULL, registration_date DATE DEFAULT NULL, okpo VARCHAR(20) DEFAULT NULL, oktmo VARCHAR(20) DEFAULT NULL, okved VARCHAR(20) DEFAULT NULL, authorized_capital NUMERIC(15, 2) DEFAULT NULL, paid_capital NUMERIC(15, 2) DEFAULT NULL, tax_system VARCHAR(50) NOT NULL, employee_count INT DEFAULT NULL, contract_count INT DEFAULT NULL, requisites JSON DEFAULT \'[]\' NOT NULL, management JSON DEFAULT NULL, founders JSON DEFAULT NULL, licenses JSON DEFAULT NULL, contact_persons JSON DEFAULT NULL, etp_accounts JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, web_site VARCHAR(255) DEFAULT NULL, office_phone VARCHAR(50) DEFAULT NULL, vat_rate VARCHAR(10) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AE93323CB ON "companies" (inn)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AA76ED395 ON "companies" (user_id)');
        $this->addSql('CREATE INDEX idx_user ON "companies" (user_id)');
        $this->addSql('CREATE INDEX idx_inn ON "companies" (inn)');
        $this->addSql('CREATE TABLE "documents" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_archived BOOLEAN DEFAULT false NOT NULL, version_comment TEXT DEFAULT NULL, doc_type VARCHAR(100) NOT NULL, status VARCHAR(255) NOT NULL, rejection_reason TEXT DEFAULT NULL, file_name_deprecated VARCHAR(255) DEFAULT NULL, file_path_deprecated TEXT DEFAULT NULL, file_size_deprecated INT DEFAULT NULL, mime_type_deprecated VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uploader_user_id INT NOT NULL, company_id INT DEFAULT NULL, application_id INT DEFAULT NULL, message_id INT DEFAULT NULL, parent_document_id INT DEFAULT NULL, uploaded_file_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2B07288537A1329 ON "documents" (message_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2B07288A8136A47 ON "documents" (parent_document_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2B07288276973A0 ON "documents" (uploaded_file_id)');
        $this->addSql('CREATE INDEX idx_uploader ON "documents" (uploader_user_id)');
        $this->addSql('CREATE INDEX idx_company ON "documents" (company_id)');
        $this->addSql('CREATE INDEX idx_doc_application ON "documents" (application_id)');
        $this->addSql('CREATE INDEX idx_message ON "documents" (message_id)');
        $this->addSql('CREATE INDEX idx_doc_status ON "documents" (status)');
        $this->addSql('CREATE INDEX idx_doc_type ON "documents" (doc_type)');
        $this->addSql('CREATE INDEX idx_uploaded_file ON "documents" (uploaded_file_id)');
        $this->addSql('CREATE TABLE leads (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_name VARCHAR(255) NOT NULL, inn VARCHAR(12) NOT NULL, contact_person VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, comment TEXT DEFAULT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, converted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, source VARCHAR(100) DEFAULT NULL, source_reference VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, assigned_to_user_id INT DEFAULT NULL, converted_to_application_id INT DEFAULT NULL, converted_to_client_id INT DEFAULT NULL, created_by_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1790455211578D11 ON leads (assigned_to_user_id)');
        $this->addSql('CREATE INDEX IDX_1790455238097A6D ON leads (converted_to_application_id)');
        $this->addSql('CREATE INDEX IDX_17904552E133240 ON leads (converted_to_client_id)');
        $this->addSql('CREATE INDEX IDX_179045527D182D95 ON leads (created_by_user_id)');
        $this->addSql('CREATE INDEX idx_leads_status ON leads (status)');
        $this->addSql('CREATE INDEX idx_leads_assigned ON leads (assigned_to_user_id, status)');
        $this->addSql('CREATE INDEX idx_leads_inn ON leads (inn)');
        $this->addSql('CREATE TABLE messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, moderation_status VARCHAR(255) NOT NULL, read_status BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, application_id INT NOT NULL, sender_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_msg_application ON messages (application_id)');
        $this->addSql('CREATE INDEX idx_sender ON messages (sender_user_id)');
        $this->addSql('CREATE INDEX idx_moderation_status ON messages (moderation_status)');
        $this->addSql('CREATE INDEX idx_msg_created_at ON messages (created_at)');
        $this->addSql('CREATE INDEX idx_msg_app_created ON messages (application_id, created_at)');
        $this->addSql('CREATE TABLE news (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_published BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "uploaded_files" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, context VARCHAR(50) NOT NULL, context_id VARCHAR(255) DEFAULT NULL, original_file_name VARCHAR(255) NOT NULL, stored_file_name VARCHAR(255) NOT NULL, storage_path VARCHAR(500) NOT NULL, file_size INT NOT NULL, mime_type VARCHAR(100) NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description TEXT DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, is_confirmed BOOLEAN DEFAULT false NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_temporary BOOLEAN DEFAULT true NOT NULL, uploaded_by_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E60EFB5861E61EA ON "uploaded_files" (uploaded_by_user_id)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, accreditation_status VARCHAR(50) DEFAULT \'pending\' NOT NULL, rejection_reason TEXT DEFAULT NULL, accreditation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fio VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, preferences JSON DEFAULT \'{}\' NOT NULL, gender VARCHAR(10) DEFAULT NULL, timezone VARCHAR(50) DEFAULT NULL, avatar_path VARCHAR(255) DEFAULT NULL, commission_rate NUMERIC(5, 2) DEFAULT NULL, personal_manager_id INT DEFAULT NULL, referrer_agent_id INT DEFAULT NULL, bank_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON "users" (email)');
        $this->addSql('CREATE INDEX idx_email ON "users" (email)');
        $this->addSql('CREATE INDEX idx_role ON "users" (role)');
        $this->addSql('CREATE INDEX idx_user_status ON "users" (status)');
        $this->addSql('CREATE INDEX idx_user_accreditation ON "users" (accreditation_status)');
        $this->addSql('CREATE INDEX idx_referrer_agent ON "users" (referrer_agent_id)');
        $this->addSql('CREATE INDEX idx_personal_manager ON "users" (personal_manager_id)');
        $this->addSql('CREATE INDEX idx_user_bank ON "users" (bank_id)');
        $this->addSql('CREATE INDEX idx_role_status ON "users" (role, status)');
        $this->addSql('ALTER TABLE agent_client_interactions ADD CONSTRAINT FK_102AF1C8753DB13F FOREIGN KEY (agent_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agent_client_interactions ADD CONSTRAINT FK_102AF1C8F55397E8 FOREIGN KEY (client_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agent_commissions ADD CONSTRAINT FK_EE6C288C753DB13F FOREIGN KEY (agent_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agent_commissions ADD CONSTRAINT FK_EE6C288C3E030ACD FOREIGN KEY (application_id) REFERENCES applications (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application_status_history ADD CONSTRAINT FK_48A559FE3E030ACD FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application_status_history ADD CONSTRAINT FK_48A559FEC20FFD1C FOREIGN KEY (changed_by_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0F55397E8 FOREIGN KEY (client_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0753DB13F FOREIGN KEY (agent_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F011C8FB41 FOREIGN KEY (bank_id) REFERENCES banks (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client_agent_link ADD CONSTRAINT FK_B631E53753DB13F FOREIGN KEY (agent_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client_agent_link ADD CONSTRAINT FK_B631E53F55397E8 FOREIGN KEY (client_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "companies" ADD CONSTRAINT FK_8244AA3AA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288CC16E2A2 FOREIGN KEY (uploader_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B072883E030ACD FOREIGN KEY (application_id) REFERENCES applications (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288537A1329 FOREIGN KEY (message_id) REFERENCES messages (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288A8136A47 FOREIGN KEY (parent_document_id) REFERENCES "documents" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "documents" ADD CONSTRAINT FK_A2B07288276973A0 FOREIGN KEY (uploaded_file_id) REFERENCES "uploaded_files" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_1790455211578D11 FOREIGN KEY (assigned_to_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_1790455238097A6D FOREIGN KEY (converted_to_application_id) REFERENCES applications (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_17904552E133240 FOREIGN KEY (converted_to_client_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_179045527D182D95 FOREIGN KEY (created_by_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E963E030ACD FOREIGN KEY (application_id) REFERENCES applications (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E962A98155E FOREIGN KEY (sender_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "uploaded_files" ADD CONSTRAINT FK_E60EFB5861E61EA FOREIGN KEY (uploaded_by_user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E938EE93C3 FOREIGN KEY (personal_manager_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E96FFE1673 FOREIGN KEY (referrer_agent_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E911C8FB41 FOREIGN KEY (bank_id) REFERENCES banks (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent_client_interactions DROP CONSTRAINT FK_102AF1C8753DB13F');
        $this->addSql('ALTER TABLE agent_client_interactions DROP CONSTRAINT FK_102AF1C8F55397E8');
        $this->addSql('ALTER TABLE agent_commissions DROP CONSTRAINT FK_EE6C288C753DB13F');
        $this->addSql('ALTER TABLE agent_commissions DROP CONSTRAINT FK_EE6C288C3E030ACD');
        $this->addSql('ALTER TABLE application_status_history DROP CONSTRAINT FK_48A559FE3E030ACD');
        $this->addSql('ALTER TABLE application_status_history DROP CONSTRAINT FK_48A559FEC20FFD1C');
        $this->addSql('ALTER TABLE applications DROP CONSTRAINT FK_F7C966F0F55397E8');
        $this->addSql('ALTER TABLE applications DROP CONSTRAINT FK_F7C966F0753DB13F');
        $this->addSql('ALTER TABLE applications DROP CONSTRAINT FK_F7C966F011C8FB41');
        $this->addSql('ALTER TABLE client_agent_link DROP CONSTRAINT FK_B631E53753DB13F');
        $this->addSql('ALTER TABLE client_agent_link DROP CONSTRAINT FK_B631E53F55397E8');
        $this->addSql('ALTER TABLE "companies" DROP CONSTRAINT FK_8244AA3AA76ED395');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288CC16E2A2');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288979B1AD6');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B072883E030ACD');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288537A1329');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288A8136A47');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288276973A0');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_1790455211578D11');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_1790455238097A6D');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_17904552E133240');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_179045527D182D95');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E963E030ACD');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E962A98155E');
        $this->addSql('ALTER TABLE "uploaded_files" DROP CONSTRAINT FK_E60EFB5861E61EA');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E938EE93C3');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E96FFE1673');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E911C8FB41');
        $this->addSql('DROP TABLE agent_client_interactions');
        $this->addSql('DROP TABLE agent_commissions');
        $this->addSql('DROP TABLE application_status_history');
        $this->addSql('DROP TABLE applications');
        $this->addSql('DROP TABLE banks');
        $this->addSql('DROP TABLE client_agent_link');
        $this->addSql('DROP TABLE "companies"');
        $this->addSql('DROP TABLE "documents"');
        $this->addSql('DROP TABLE leads');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE "uploaded_files"');
        $this->addSql('DROP TABLE "users"');
    }
}
