# C:\Users\Maral\PhpstormProjects\leader_grant_backend\docker\nginx\default.conf

server {
    listen 80;
    server_name localhost;
    root /var/www/project/public; # <--- Корень сайта = папка /public

    # Главная логика Symfony
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # "Проксируем" .php файлы на сервис 'php' (FPM)
    location ~ \.php$ {
        fastcgi_pass   php:9000; # <--- 'php' - это имя сервиса из docker-compose
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
}
