# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(CHECKO_API_KEY): ''
    env(EIS_API_KEY): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            # --- Исключаем ядро и DI ---
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

            # --- Исключаем ВСЕ папки Entity ---
            - '../src/Application/Entity/'
            - '../src/Bank/Entity/'
            - '../src/Chat/Entity/'
            - '../src/Document/Entity/'
            - '../src/User/Entity/'

            # --- Исключаем ВСЕ папки DTO ---
            - '../src/Application/DTO/'
            - '../src/Chat/DTO/'
            - '../src/Integration/DTO/'
            - '../src/Shared/DTO/'
            - '../src/User/DTO/'
            - '../src/News/Entity/'
            - '../src/News/DTO/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Shared\Infrastructure\ApiExceptionListener:
        arguments:
            $logger: '@logger'             # Внедрить сервис логгера
            $isDebug: '%kernel.debug%'    # Внедрить "режим отладки" (true/false)
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # 2. Связь для Checko
    App\Integration\Client\CheckoApiClient:
        arguments:
            $checkoApiKey: '%env(CHECKO_API_KEY)%'

    # 3. Связь для ЕИС (Тендеры)
    App\Integration\Client\TenderApiClient:
        arguments:
            $eisApiKey: '%env(EIS_API_KEY)%'

    # "Связываем" абстракцию FilesystemOperator с нашим конкретным хранилищем
    # для DocumentService
    App\Document\Service\DocumentService:
        arguments:
            # '@default.storage' - это имя сервиса из flysystem.yaml
           # $defaultStorage: '@default.storage'

    # Связываем хранилища для UploadService
    App\Upload\Service\UploadService:
        arguments:
            $publicStorage: '@public.storage'
            $privateStorage: '@default.storage'
